### ISSUE TITLE
Introduce YAML configuration file

### ISSUE THREAD

**Issue by bartoszmajsak** [arquillian/smart-testing#113]
In order to simplify user experience, we should introduce configuration file and use system properties as special-cases overwrite strategy instead of default approach as we are doing now.

This task is to map all generic configuration we have in place to a YAML stored in the root of the project named `smart-testing.yaml`. 

- [x] file becomes a prerequisite/enabler of our extension if `smart.testing.strategies` property not used
- [x] keep the same defaults as with properties
- [ ] update documentation
- [ ] update `Test Bed` to follow new approach

**Comment by dipak-pawar** [comment]
This is how simple yaml configuration file as starting point
```yaml
  - mode: ordering
  - strategies:
    - new
    - changed
    - affected
  - applyto: failsafe,surefire
  - debug: true
  - disable: true
  - report:
    - enable: true
    - name: smart-testing.xml
    - dir: smart-testing
  - scm:
    - range:
      - head: HEAD
      - tail: HEAD~3
    - lastchanges: 3
```

**Comment by bartoszmajsak** [comment]
Minor detail: I think it should be without leading `-`
```yaml
strategies:
  - new
  - changed
  - affected
applyto: failsafe,surefire
```
this is a bit inconsistent. We should either have proper yaml array or comma-separated values.

I would also say that `report: enable: true` should be optional, meaning that if there is name and dir specified it is enabled. so only `enable: false` would make any sense. WDYT?

`dir: smart-testing`

Is maybe a bit blurry. What do we support here? If relative path than based on the root folder? absolute paths too?
