### ISSUE TITLE
Add support for configuring strategies separately

### ISSUE THREAD

**Issue by MatousJobanek** [arquillian/smart-testing#207]
##### Issue Overview

We have great YAML config file: http://arquillian.org/smart-testing/#_configuration_file where we can configure the general information. Now, we should support also the possibility to configure each strategy separately (eg. [inclusions and exclusions for affected one](http://arquillian.org/smart-testing/#_strategies_2))

example:
```yaml
mode: ordering 
strategies: new, changed, affected 
debug: true 
report:
    enable: true 
affected:
    inclusion:
        - org.package.*
        - org.arquillian.package.*
    exclusions:
        - org.package.exclude.*
        - org.arquillian.package.exclude.*
    
```
